default:
    just -g --list

# Start a new NeoVim session in the current directory with tmux split-window
nvim-dev:
    tmux new-session -A -snvim-dev \; split-window -v -l 20 \; select-pane -t 0 \; send-keys "nvim" C-m \;

[macos]
_reboot_darwin:
    osascript -e 'tell app "System Events" to restart'

[macos]
_shutdown_darwin:
    osascript -e 'tell app "System Events" to shut down'

[linux]
_reboot_linux:
    systemctl reboot

[linux]
_shutdown_linux:
    systemctl poweroff

# Reboot computer
[group("System")]
[confirm("Are you sure you want to reboot")]
reboot:
    if $(uname) == "Darwin" {
        just _reboot_darwin
    } else {
        just _reboot_linux
    }

# Shut down computer
[group("System")]
[confirm("Are you sure you want to shut down")]
reboot:
    if $(uname) == "Darwin" {
        just _shutdown_darwin
    } else {
        just _shutdown_linux
    }
