autoload -U +X bashcompinit && bashcompinit
autoload -Uz compinit
compinit

# Aliases
alias cl=clear
alias ..="cd .."
alias ...="cd ../.."
alias justg="just --global-justfile"

# Autocomplete
bindkey '^w' autosuggest-execute
bindkey '^e' autosuggest-accept
bindkey '^u' autosuggest-toggle
bindkey '^L' vi-forward-word
bindkey '^k' up-line-or-search
bindkey '^j' down-line-or-search

# Enviroment
export EDITOR="$(which nvim)"
export XDG_CONFIG_HOME="$HOME/.config"

# Homebrew
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"

if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi

# Golang
export GOPATH="$HOME/go"
PATH="$GOPATH/bin:$PATH"

# Rust builds
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
export CC=/opt/homebrew/opt/llvm/bin/clang
export AR=/opt/homebrew/opt/llvm/bin/llvm-ar
source <(rustup completions zsh cargo)

# AWS
alias awsp="source _awsp"
complete -C '/usr/local/bin/aws_completer' aws

# Startship
eval "$(starship init zsh)"
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"

# TheFuck
eval $(thefuck --alias)

# Git cliff
export GIT_CLIFF_CONFIG="$HOME/.config/git-cliff/cliff.toml"

# Draw.io
alias drawio="/Applications/draw.io.app/Contents/MacOS/draw.io"

# Just
eval $(just --completions zsh)

# Eza
alias l="eza -l --icons --git -a"
alias lt="eza --tree --level=2 --long --icons --git"
alias ltree="eza --tree --level=2  --icons --git"

# FZF
source <(fzf --zsh)
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow'

# Zoxide
eval "$(zoxide init zsh)"

# Kubectl
source <(kubectl completion zsh)

# Prettierd
export PRETTIERD_DEFAULT_CONFIG="$HOME/.config/prettierd/default.json"
