# Autocomplete
bindkey '^w' autosuggest-execute
bindkey '^e' autosuggest-accept
bindkey '^u' autosuggest-toggle
bindkey '^L' vi-forward-word
bindkey '^k' up-line-or-search
bindkey '^j' down-line-or-search

# AWS
alias awsp="source _awsp"

# Startship
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"

# TheFuck
eval $(thefuck --alias)

# Git cliff
export GIT_CLIFF_CONFIG="$HOME/.config/git-cliff/cliff.toml"

# Draw.io
alias drawio="/Applications/draw.io.app/Contents/MacOS/draw.io"

# Just
eval $(just --completions zsh)

# FZF
source <(fzf --zsh)
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow'

# Kubectl
source <(kubectl completion zsh)

# Prettierd
export PRETTIERD_DEFAULT_CONFIG="$HOME/.config/prettierd/default.json"
