autoload -U +X bashcompinit && bashcompinit
autoload -Uz compinit
compinit

# Autocomplete
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
bindkey '^w' autosuggest-execute
bindkey '^e' autosuggest-accept
bindkey '^u' autosuggest-toggle
bindkey '^L' vi-forward-word
bindkey '^k' up-line-or-search
bindkey '^j' down-line-or-search

# Enviroment
export EDITOR=/opt/homebrew/bin/nvim
export XDG_CONFIG_HOME="$HOME/.config"

# Homebrew
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"

if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

  autoload -Uz compinit
  compinit
fi

# Golang
export GOPATH="$HOME/go"
PATH="$GOPATH/bin:$PATH"

# Rust builds
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
export CC=/opt/homebrew/opt/llvm/bin/clang
export AR=/opt/homebrew/opt/llvm/bin/llvm-ar
source <(rustup completions zsh cargo)
source <(rustup completions zsh)

# AWS
complete -C '/usr/local/bin/aws_completer' aws

# Angular CLI
source <(ng completion script)

# Startship
eval "$(starship init zsh)"
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"

# TheFuck
eval $(thefuck --alias)

# Git cliff
export GIT_CLIFF_CONFIG="$HOME/.config/git-cliff/cliff.toml"  # Config file path 

# Draw.io
alias drawio="/Applications/draw.io.app/Contents/MacOS/draw.io"

# Terragrunt
complete -o nospace -C /opt/homebrew/bin/terragrunt terragrunt

# Just
eval $(just --completions zsh)

# Eza
alias l="eza -l --icons --git -a"
alias lt="eza --tree --level=2 --long --icons --git"
alias ltree="eza --tree --level=2  --icons --git"

# FZF
source <(fzf --zsh)
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow'

# Zoxide
eval "$(zoxide init zsh)"

# Kubectl
source <(kubectl completion zsh)
